from sage.all import *
import time, traceback

proof.all(True)
pari.allocatemem(3_000_000_000)

# Reciprocal bielliptic quotient for (p,q)=(43,71), (m,n)=(57,14).
Eorig = EllipticCurve(QQ, [0,
    164592131218369,
    0,
    6688154288713723299763380000,
    79395460176636941951814993631822707360000])
Emin = EllipticCurve(QQ, [1,0,0,
    -146377224851325609522351670,
    667886864751009985149216219926929986212])
phi = Emin.isomorphism_to(Eorig)

print('HEEGNER_START', flush=True)
print('EMIN', Emin, flush=True)
print('EORIG', Eorig, flush=True)
print('CONDUCTOR', Emin.conductor(), flush=True)
print('ROOT_NUMBER', Emin.root_number(), flush=True)
print('ANALYTIC_RANK', Emin.analytic_rank(), flush=True)
print('RANK_SAGE', Emin.rank(proof=True, only_use_mwrank=False), flush=True)

PE = pari.ellinit(pari(list(Emin.a_invariants())))
print('PARI_ELLINIT_OK', flush=True)

t0=time.time()
try:
    h = pari.ellheegner(PE)
    print('ELLHEEGNER_RAW', h, flush=True)
    print('ELLHEEGNER_SECONDS', time.time()-t0, flush=True)
    if len(h) < 2:
        raise RuntimeError('ellheegner returned no affine point')
    hx = QQ(h[0].sage())
    hy = QQ(h[1].sage())
    Pmin = Emin(hx,hy)
    Porig = phi(Pmin)
    print('PMIN', Pmin, flush=True)
    print('PORIG', Porig, flush=True)
    print('HEIGHT_MIN', Pmin.height(), flush=True)
    print('HEIGHT_ORIG', Porig.height(), flush=True)
    assert Pmin in Emin and Porig in Eorig

    # Saturate the subgroup generated by the Heegner point.
    try:
        sat = Emin.saturation([Pmin], max_prime=100000, proof=True)
        print('SATURATION', sat, flush=True)
    except Exception as exc:
        print('SATURATION_ERROR', repr(exc), flush=True)
        traceback.print_exc()

    # Seed Sage's known-point cache, then ask for a proof-enabled basis.
    try:
        Emin._known_points = [Pmin]
        gens = Emin.gens(proof=True)
        print('PROVEN_GENS_MIN', gens, flush=True)
        print('PROVEN_GENS_ORIG', [phi(Q) for Q in gens], flush=True)
    except Exception as exc:
        print('PROVEN_GENS_ERROR', repr(exc), flush=True)
        traceback.print_exc()

    open('heegner-43-71-point.txt','w').write(
        'Pmin=%s\nPorig=%s\nheight=%s\n' % (Pmin,Porig,Pmin.height()))
    print('HEEGNER_POINT_FOUND True', flush=True)
except Exception as exc:
    print('HEEGNER_ERROR', repr(exc), flush=True)
    traceback.print_exc()
    print('HEEGNER_POINT_FOUND False', flush=True)

print('HEEGNER_COMPLETE True', flush=True)
